### ISSUE TITLE
Keycloak login template causes HTTP 500 on login for clients missing Client Name

### ISSUE THREAD

**Issue by sharpedavid** [bcgov/moh-iam#7]
Need to do a null check on this line:

https://github.com/bcgov/moh-iam/blob/a1d215650cd18eca4416c35e300038aa41f5b514/keycloak-themes/moh-app-realm/login/login.ftl#L4

Check other templates for similar issues if applicable. Ideally the template should work as long as all mandatory attributes (mandatory in Keycloak) are provided.

**Comment by ahoplock** [comment]
Fixed as of https://github.com/bcgov/moh-iam/pull/25
